### PR TITLE
this project is completed(need check)

### PR DESCRIPTION
**Pull request by AndriiYelieva**
[DEMO LINK](https://AndriiYelieva.github.io/react_phone-catalog/)

### CODE REVIEW

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
.

**Review by VitaliyBodnar — CHANGES_REQUESTED** [review]
- All tests are not passed 
Screenshot 2023-09-09 at 14 22 06

**Review by sTorba24 — CHANGES_REQUESTED** [review]
Well done!


1. should be device name here and in breadcrumbs
image

2.now here are 5 items in cart
image
 
3. search isn't working 
image


4. add mobile and tablet version :)

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
1. Add transition for hover effects
image

2. Will be better if you add hover effects for all clickable elements
image

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
1. These links should be opened in the new tab
image

2. I think it would be better if the product disappears from the shopping cart when you click on this button
image

**Review by VitaliyBondarenko1982 — APPROVED** [review]
Looks good

**Pull request closed without merging**
