### PR TITLE
The task is completed

### PR DESCRIPTION
**Pull request by AndruhaMan**
[DEMO PAGE](https://andruhaman.github.io/react_phone-catalog/)

### CODE REVIEW

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Great work 👍 
1. Add the indents between the images and buttons in slider
image

**Review by etojeDenys — CHANGES_REQUESTED** [review]
layout looks good just adjust for mobiles, tablets

**Review by sTorba24 — CHANGES_REQUESTED** [review]
Did you run deploy? Your changes didn't apply and mobile looks broken :(

image

**Comment by AndruhaMan** [comment]
> Did you run deploy? Your changes didn't apply and mobile looks broken :(
> 
> image

Sorry, I forgot about this. It is deployed now

**Review by sTorba24 — CHANGES_REQUESTED** [review]
Are you sure it's working correct? Stills look broken :(
image

**Comment by AndruhaMan** [comment]
> Are you sure it's working correct? Stills look broken :( image

image

On my device it looks some better)

**Review by etojeDenys — APPROVED** [review]
lgtm

**Review by anastasiiavorobiova — COMMENTED** [review]
Great work!

**Pull request closed without merging**
