### PR TITLE
Created a catalog

### PR DESCRIPTION
**Pull request by dmitrymatvichuk**
https://dmitrymatvichuk.github.io/react_phone-catalog/

### CODE REVIEW

**Review by DarkMistyRoom — CHANGES_REQUESTED** [review]
- please fix these warnings
image

- this hover effect looks a bit rough because of no indent on the left of the text
image

- please remove the horizontal scroll from mobile screen
- would be great to add some indent here
image

**Comment by dmitrymatvichuk** [comment]
I fixed errors in the code and styles.

**Comment by dmitrymatvichuk** [comment]
I fixed the page, I don't like the decision to hide the button, the footer looks empty.

**Review by maxim2310 — APPROVED** [review]
Well done!!!

**Pull request closed without merging**
