### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by savchuksavchuk**
[DEMO LINK](https://savchuksavchuk.github.io/react_phone-catalog/)

### CODE REVIEW

**Comment by savchuksavchuk** [comment]
Sorry, problems with images. Going to fix it.

**Review by qoa11a — CHANGES_REQUESTED** [review]
1. when I open the demo link it gives me a non-existent page
2. when I update your app on any existent page it gives a 404
image
3. I can click the prev arrow on the 1st page and the next arrow on the last one. They should be disabled in such cases

4. problems with images that you've mentioned yourself

**Review by Anastasiia-Svintsova — CHANGES_REQUESTED** [review]
- Fix these links. They can lead to the not found page or page in development, for example. But not to 404

https://user-images.githubusercontent.com/99403198/218094137-fefd7641-b917-4550-a662-2c57923d2f7e.mov

- try to pass all tests 
image

- Check the images' src 

https://user-images.githubusercontent.com/99403198/218094477-511e236a-6ef0-42c9-a903-3e83a2f7285d.mov

- Would be great to add some styles for small screens. It's not necessary, but will look much better in your portfolio 
image

**Comment by savchuksavchuk** [comment]
I don't know why, but I cant run tests on my pc. They are running nearly 1 hour wihout any result.

**Comment by savchuksavchuk** [comment]
Even after deploy test are finished in 4 hours(

**Review by witflash — APPROVED** [review]
Well done 👍 

Additionally, you can try to implement page count in URL param: 
image

**Pull request closed without merging**
