### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by no4kar**
[DEMO LINK](https://no4kar.github.io/react_phone-catalog/)

### CODE REVIEW

**Review by anastasiia-tilikina — CHANGES_REQUESTED** [review]
Good job!

pls watch the [video](https://www.loom.com/share/c4cf1be71ae043c685bdddf2c1bb882a?sid=1fd99081-48a5-4e3b-81a7-719a3a7ff821) and fix issues

**Review by DarkMistyRoom — CHANGES_REQUESTED** [review]
- add some right indent to these arrows
image

- add the navigation buttons to the Cart page
image

**Review by IvanFesenko — CHANGES_REQUESTED** [review]
Good good. Some not implemented items left:
- add  favIcon
- Back button not works. NOTE: it should leads to phones page, not previous color
2023-12-28_15h02_10

**Review by Esceype — APPROVED** [review]
Well done!

**Pull request closed without merging**
