### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by donizer**
The project is written using Tailwind and React-Select

Also, I disabled tests because they don't leave logs, so it's hard to understand what exactly is wrong.

~[DEMO LINK](https://donizer.github.io/react_phone-catalog/)~

Edit: Since I skipped tests I decided move to Vite because it's more convenient for me. New repository and demo link below:

[DEMO LINK](https://donizer.github.io/vite_react_phone-catalog/)
[REPO](https://github.com/donizer/vite_react_phone-catalog)

### CODE REVIEW

**Review by denys-danyliuk — CHANGES_REQUESTED** [review]
add some favicon

add hover effects to this elements
Знімок екрана 2023-11-22 о 16 39 53

change this button text and would be great to change how it looks when user click on it, now it's unclear whether it's added or not, also add transition to it and to all other interactive elements
Знімок екрана 2023-11-22 о 16 39 36

make some popup instead of this text
Знімок екрана 2023-11-22 о 16 41 46

because you add search params after user goes by the link it takes two click to go to the previous page
Знімок екрана 2023-11-22 о 16 42 43

add transition, also add cursor pointer when hovering over interactive elements
Знімок екрана 2023-11-22 о 16 43 46

when user is searching for some phone ui is 'jumping' for lack of a better word, use debounce and filter the list after some time
https://github.com/mate-academy/react_phone-catalog/assets/106310796/95d38658-c69b-4e99-aff8-8d8710c66e27

**Comment by donizer** [comment]
New repository and demo link:

[DEMO LINK](https://donizer.github.io/vite_react_phone-catalog/)
[REPO](https://github.com/donizer/vite_react_phone-catalog)

**Review by IvanFesenko — CHANGES_REQUESTED** [review]
Pay attention on page view during catalog selection
https://github.com/mate-academy/react_phone-catalog/assets/61904995/9e0a7033-a3d6-44fc-9837-56ea41b710c3

Fix this case 
https://github.com/mate-academy/react_phone-catalog/assets/61904995/cf77b33f-87e4-4592-a740-36a42b393c76

In my mind upper count should show number of items not amount. On that case should be 1
2023-11-23_16h29_05

**Review by TarasHoliuk — APPROVED** [review]
Amazing :fire: 
Approved :heavy_check_mark:

**Pull request closed without merging**
